title: Yakhyo's Page
description: HiğŸ– Glad to see you hereğŸ™‚
logo: assets/logo.png
show_downloads: true
minima:
  social_links:
    twitter: jekyllrb
    github: jekyll

preferences:
  - type: dropdown
    name: language
    label: Language
    description: Choose your preferred language.
    options:
      - label: English
        value: en
      - label: Uzbek
        value: uz
#theme: jekyll-theme-minimal
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag